# Site settings
title:       banesto.github.io
email:       ernests.kecko@gmail.com
author:      Ernests Kečko
description: "get it goin'"
baseurl:     ""
url:         "http://banesto.github.io"
date_format: "%b %-d, %Y"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:    banesto
bitbucket_username:
stackoverflow_id:   484363
twitter_username:   mezadurejs
google_plus_id:
linkedin_username:  ernestskecko
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
